name = "ecommerce-frontend"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
NEXT_PUBLIC_API_URL = "https://your-production-api-url.com"
NEXT_PUBLIC_GOOGLE_CLIENT_ID = "your-google-client-id"